version: '3.1'
name: 'calvary-admin-system'

services:
  admin-app:
    build: './admin-app'
    container_name: 'calvary-admin-app'
    restart: always
    ports:
      - 3000:3000
    networks:
      - calvary-network
    depends_on:
      - main-service
  
  main-service:
    build: './main-service'
    container_name: 'calvary-main-service'
    restart: always
    ports:
      - 8080:8080
    networks:
      - calvary-network
    depends_on:
      - postgres
    env_file:
      - "./main-service/.env"
    volumes:
      - ./uploads:/app/uploads
    
  postgres:
    image: postgres:12.1-alpine
    container_name: 'calvary-postgres'
    restart: always
    environment:
      POSTGRES_USER: calvary
      POSTGRES_PASSWORD: calvary@123
      POSTGRES_DB: calvary
    ports:
      - 5432:5432
    networks:
      - calvary-network
    volumes:
      - postgres-data:/var/lib/postgresql/data
  
  adminer:
    image: adminer
    container_name: 'calvary-adminer'
    restart: always
    ports:
      - 8082:8080
    networks:
      - calvary-network
    depends_on:
      - postgres

volumes:
  postgres-data:

networks:
  calvary-network:
    driver: bridge
