import SidebarLayout from "@/components/SidebarLayout";
import { QueryProvider } from "@/context/QueryContext";
import { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <>
      <html lang="en" className="h-full bg-white">
        <QueryProvider>
          <body className="h-full">
            <SidebarLayout>{children}</SidebarLayout>
          </body>
        </QueryProvider>
      </html>
    </>
  );
}
